### ISSUE TITLE
compatibility inquiry

### ISSUE THREAD

**Issue by oknyshuk** [sadaszewski/freebsd-patch-geli-password-from-tpm2#1]
does this still work? I want to install FreeBSD 14.0R, and this feature is a must-have for me. also, can I later get binary updates, or do I have to patch every update and compile it from source for this to keep working?

**Comment by oknyshuk** [comment]
@sadaszewski?

**Comment by sadaszewski** [comment]
Thanks for reaching out. Yes, it should work with FreeBSD 14.0 and no,
there is no binary update mechanism. You have to recompile the kernel (and
bootloader if you update it as well) each time.

**Comment by oknyshuk** [comment]
thank you for replying!
